"""empty message

Revision ID: 5955e7e0a160
Revises: 943ee758e957
Create Date: 2018-10-03 13:54:59.227516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5955e7e0a160'
down_revision = '943ee758e957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('with_drawal', sa.Column('amount', sa.String(length=159), nullable=True))
    op.add_column('with_drawal', sa.Column('reason', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('with_drawal', 'reason')
    op.drop_column('with_drawal', 'amount')
    # ### end Alembic commands ###
